#!/bin/sh

# Mount the new Linux file system
#
current=$(/sbin/fw_printenv mender_boot_part | awk -F = '{ print $2 }')

if [ $current = "2" ]; then
    newroot=/dev/mmcblk0p3
elif [ $current = "3" ]; then
    newroot=/dev/mmcblk0p2
else
    echo "Unexpected current root: $current" >&2
    exit 1
fi

mount $newroot /mnt

if [ $? -ne 0 ]; then
    echo "Failed to mount $newroot" >&2
    exit 1
fi

sleep 2

# Copy host and hostname files from /data to new Linux filesystem
cp /data/etc/hostname /mnt/etc/hostname
cp /data/etc/hosts /mnt/etc/hosts

#TODO this script could be extended to copy all the other non-fungible Linux files such as /home/pi/.ssh/authorized_keys

# unmount the new Linux filesystem
umount $newroot
